config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('recipe.urls'))
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from .import views
from .views import Recipe_Post



app_name = 'recipe' 
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('blog_post/', views.BlogPost.as_view(), name='blog_post'),
    path('elements/', views.Elements.as_view(), name='elements'),
    path('post/', Recipe_Post.as_view(), name='recipe_post'),
    path('recipe-detail/<int:id>/', views.RecipeDetail.as_view(), name='recipe-detail'),
]

users/urls.py
from django.urls import path
from .views import Login,RegisterView


app_name = 'users'


urlpatterns = [
    path('login/', Login.as_view(), name='login'), 
    path('register/', RegisterView.as_view(), name='register')
]

recipe/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from users.models import User

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    star = models.IntegerField()
    image = models.ImageField(upload_to="recipes-images/")
    created_at = models.DateTimeField(auto_now_add=True)
    prep = models.IntegerField()
    cook = models.IntegerField()
    
    def __str__(self):
       return self.name

    def __str__(self) -> str:
        return f'text -> {self.name} star -> {self.star}'

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')

def __str__ (self) -> str:
    return self.name


class Comment(models.Model):
    recipe = models.ForeignKey('Recipe', related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.recipe}'


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.name
    
class CommentRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    rating = models.IntegerField(default=1)  # Rating field,  to 1 star

    def __str__(self) -> str:
        return self.text[:50]
    
    
class RecipeText(models.Model):
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    text = models.TextField()



class MainPage(models.Model):
    pass

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users-images/', default='default_profile_picture.jpg')

    def __str__(self):
        return str(self.username)

recipe/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Recipe, Ingredient,Contact, CommentRecipe
import requests
from django.urls  import reverse


class Home(View):
    def get(self, request):
        recipes = Recipe.objects.all()
        two_recipes = Recipe.objects.all().order_by()[:2]
        context = {'recipes': recipes,'two_recipes': two_recipes}
        return render(request, 'index.html', context)

class About(View):
    def get(self, request):
        return render(request, 'about.html')

class BlogPost(View):
    def get(self, request):
        return render(request, 'blog-post.html')
class ContactView(View):
    def get(self, request):
        return render(request, 'contact.html')
    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        Contact.objects.create(name=name, email=email, subject=subject, message=message)
        self.send_telegram_message(name, email, subject, message) 
        return render(request, 'index.html', {'success': 'Your message has been sent'})


    def send_telegram_message(self, name, email, subject, message):
        bot_token = '7103821725:AAEeh30tBRyByHozOg0EdNBhUFDiSv4ngEw'
        chat_id = 1913322681
        telegram_api_url = f'https://api.telegram.org/bot{bot_token}/sendMessage'
        
        xabar = f'Yangi xabar keldi\nName: {name}\nEmail: {email}\nSubject: {subject}\nMessage: {message}'

        payload = {
            'chat_id': chat_id,
            'text': xabar
        }
        response = requests.post(url=telegram_api_url, data=payload)
        if response.status_code != 200:
            print(f'Error sending message: {response.status_code}, Response: {response.text}')


class RecipeList(View):
    def get(self, request):
        recipes = Recipe.objects.all()
        context = {'recipes': recipes}
        return render(request, 'recipe-list.html', context)
class Elements(View):
    def get(self, request):
        return render(request, 'elements.html')

class Recipe_Post(View):
    
    def get(self, request, id):
        recipe = Recipe.objects.get(id=id)
        return render(request, 'receipe-post.html', {'recipe': recipe})

    def post(self, request , id):
        recipe  = Recipe.objects.get('message')
        user  = request.user
        message = request.POST.get('message')
        CommentRecipe.objects.create(user=user, recipe=recipe, text=message)
        return redirect(reverse('recipe-post'),kwargs={'id': id})
    


class RecipeDetail(View):
    def get(self, request, id):
        recipe = Recipe.objects.get(id=id)
        comments = CommentRecipe.objects.filter(recipe=recipe)
        return render(request, 'receipe-post.html', {'recipe': recipe, 'comments': comments})
    
    def post(self, request, id):
        recipe = Recipe.objects.get(id=id)
        user = request.user
        message = request.POST.get('message')
        rating = request.POST.get('rating')
        CommentRecipe.objects.create(user=user, recipe=recipe, text=message, rating=rating)
        return redirect(reverse('recipe-detail', kwargs={'id': id}))
    
    
    
    
    

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .models import User

class Login(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        messages.error(request, 'Invalid credentials')
        return render(request, 'login.html')

class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        password_repeat = request.POST.get('password_repeat')
        
        if password != password_repeat:
            messages.error(request, 'Passwords do not match')
            return render(request, 'register.html')

        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exists')
            return render(request, 'register.html')
        
        User.objects.create_user(username=username, password=password)
        messages.success(request, 'Account created successfully')
        return redirect('users:login')

recipe/templates/contact.html
{% extends "base.html" %}

{% block content %}

  <!-- ##### Breadcumb Area Start ##### -->
  <div class="breadcumb-area bg-img bg-overlay" style="background-image: url(img/bg-img/breadcumb4.jpg);">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcumb-text text-center">
                    <h2>Recipe</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->

<!-- ##### Contact Information Area Start ##### -->
<div class="contact-information-area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="logo mb-80">
                    <img src="img/core-img/logo.png" alt="">
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Contact Text -->
            <div class="col-12 col-lg-5">
                <div class="contact-text">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec varius dui. Suspendisse potenti. Vestibulum ac pellentesque tortor. Aenean congue sed metus in iaculis. Cras a tortor enim. Phasellus posuere vestibulum ipsum, eget lobortis purus.</p>
                    <p>Orci varius natoque penatibus et magnis dis ac pellentesque tortor. Aenean congue parturient montes, nascetur ridiculus mus.</p>
                </div>
            </div>

            <div class="col-12 col-lg-3">
                <!-- Single Contact Information -->
                <div class="single-contact-information mb-30">
                    <h6>Address:</h6>
                    <p>481 Creekside Lane Avila <br>Beach, CA 93424</p>
                </div>
                <!-- Single Contact Information -->
                <div class="single-contact-information mb-30">
                    <h6>Phone:</h6>
                    <p>+53 345 7953 32453 <br>+53 345 7557 822112</p>
                </div>
                <!-- Single Contact Information -->
                <div class="single-contact-information mb-30">
                    <h6>Email:</h6>
                    <p>yourmail@gmail.com</p>
                </div>
            </div>

            <!-- Newsletter Area -->
            <div class="col-12 col-lg-4">
                <div class="newsletter-form bg-img bg-overlay" style="background-image: url(img/bg-img/bg1.jpg);">
                    <form action="#" method="post">
                        <input type="email" name="email" placeholder="Subscribe to newsletter">
                        <button type="submit" class="btn delicious-btn w-100">Subscribe</button>
                    </form>
                    <p>Fusce nec ante vitae lacus aliquet vulputate. Donec sceleri sque accumsan molestie.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Contact Information Area End ##### -->

<!-- ##### Contact Form Area Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h3>Get In Touch</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="contact-form-area">
                    <form action="{% url 'recipe:contact' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <input name="name" type="text" class="form-control" id="name" placeholder="Name">
                            </div>
                            <div class="col-12 col-lg-6">
                                <input name="email" type="email" class="form-control" id="email" placeholder="E-mail">
                            </div>
                            <div class="col-12">
                                <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject">
                            </div>
                            <div class="col-12">
                                <textarea name="message" class="form-control" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn delicious-btn mt-30" type="submit">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Contact Form Area End ##### -->

<!-- ##### Google Maps ##### -->
<div class="map-area">
    <div id="googleMap"></div>
</div>

{% endblock content %}

recipe/templates/index.html
{% extends "base.html" %}

{% block content %}
  <!-- ##### Hero Area Start ##### -->
  <section class="hero-area">
    <div class="hero-slides owl-carousel">
        {% for recipe in recipes %}

        <!-- Single Hero Slide -->
        <div class="single-hero-slide bg-img" style="background-image: url({{recipe.image.url}});">
            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="hero-slides-content" data-animation="fadeInUp" data-delay="100ms">
                            <h2 data-animation="fadeInUp" data-delay="300ms">{{ recipe.name }}</h2>
                            <p data-animation="fadeInUp" data-delay="700ms">{{ recipe.text.text }}</p>
                            <a href="{% url 'recipe:recipe-detail' id=recipe.id %}" class="btn delicious-btn" data-animation="fadeInUp" data-delay="1000ms">See Receipe</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<!-- ##### Hero Area End ##### -->

<!-- ##### Top Catagory Area Start ##### -->
<section class="top-catagory-area section-padding-80-0">
    <div class="container">
        <div class="row">
            {% for two_recipe in two_recipes %}
            <!-- Top Catagory Area -->
            <div class="col-12 col-lg-6">
                <div class="single-top-catagory">
                    <img src="{{two_recipe.image.url}}" alt="">
                    <!-- Content -->
                    <div class="top-cta-content">
                        <h3>{{two_recipe.name}}</h3>
                        <h6>Simple &amp; Delicios</h6>
                        <a href="{% url 'recipe:recipe-detail' id=two_recipe.id %}" class="btn delicious-btn">See Full Receipe</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- ##### Top Catagory Area End ##### -->

<!-- ##### Best Receipe Area Start ##### -->
<section class="best-receipe-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h3>The best Receipies</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Single Best Receipe Area -->
            {% for recipe in recipes %}
            <div class="col-12 col-sm-6 col-lg-4">
                <div class="single-best-receipe-area mb-30">
                    <img src="{{recipe.image.url}}" alt="">
                    <div class="receipe-content">
                        <a href="{% url 'recipe:recipe-detail' id=recipe.id %}">
                            <h5>{{recipe.name}}</h5>
                        </a>
                        <div class="ratings">
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star-o" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- ##### Best Receipe Area End ##### -->

<!-- ##### CTA Area Start ##### -->
<section class="cta-area bg-img bg-overlay" style="background-image: url(/static/img/bg-img/bg4.jpg);">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <!-- Cta Content -->
                <div class="cta-content text-center">
                    <h2>Gluten Free Receipies</h2>
                    <p>Fusce nec ante vitae lacus aliquet vulputate. Donec scelerisque accumsan molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras sed accumsan neque. Ut vulputate, lectus vel aliquam congue, risus leo elementum nibh</p>
                    <a href="#" class="btn delicious-btn">Discover all the receipies</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### CTA Area End ##### -->

<!-- ##### Small Receipe Area Start ##### -->
<section class="small-receipe-area section-padding-80-0">
    <div class="container">
        <div class="row">

          <!-- Small Receipe Area -->
          {% for recipe in recipes %}
          <div class="col-12 col-sm-6 col-lg-4">
              <div class="single-small-receipe-area d-flex">
                  <!-- Receipe Thumb -->
                  <div class="receipe-thumb">
                      <img src="{{recipe.image.url}}" alt="">
                  </div>
                  <!-- Receipe Content -->
                  <div class="receipe-content">
                      <span>{{recipe.created_at}}</span>
                      <a href="{% url 'recipe:recipe-detail' id=recipe.id %}">
                          <h5>Homemade italian pasta</h5>
                      </a>
                      <div class="ratings">
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star-o" aria-hidden="true"></i>
                      </div>
                      <p>{{recipe.comments.count}}</p>
                  </div>
              </div>
          </div>
          {% endfor %}
        </div>
    </div>
</section>
<!-- ##### Small Receipe Area End ##### -->

<!-- ##### Quote Subscribe Area Start ##### -->
<section class="quote-subscribe-adds">
    <div class="container">
        <div class="row align-items-end">
            <!-- Quote -->
            <div class="col-12 col-lg-4">
                <div class="quote-area text-center">
                    <span>"</span>
                    <h4>Nothing is better than going home to family and eating good food and relaxing</h4>
                    <p>John Smith</p>
                    <div class="date-comments d-flex justify-content-between">
                        <div class="date">January 04, 2018</div>
                        <div class="comments">2 Comments</div>
                    </div>
                </div>
            </div>

            <!-- Newsletter -->
            <div class="col-12 col-lg-4">
                <div class="newsletter-area">
                    <h4>Subscribe to our newsletter</h4>
                    <!-- Form -->
                    <div class="newsletter-form bg-img bg-overlay" style="background-image: url(/static/img/bg-img/bg1.jpg);">
                        <form action="#" method="post">
                            <input type="email" name="email" placeholder="Subscribe to newsletter">
                            <button type="submit" class="btn delicious-btn w-100">Subscribe</button>
                        </form>
                        <p>Fusce nec ante vitae lacus aliquet vulputate. Donec sceleri sque accumsan molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.</p>
                    </div>
                </div>
            </div>

            <!-- Adds -->
            <div class="col-12 col-lg-4">
                <div class="delicious-add">
                    <img src="/static/img/bg-img/add.png" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Quote Subscribe Area End ##### -->
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Delicious - Food Blog Template | Home</title>

    <!-- Favicon -->
    <link rel="icon" href="/static/img/core-img/favicon.ico">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <i class="circle-preloader"></i>
        <img src="/static/img/core-img/salad.png" alt="">
    </div>

    <!-- Search Wrapper -->
    <div class="search-wrapper">
        <!-- Close Btn -->
        <div class="close-btn"><i class="fa fa-times" aria-hidden="true"></i></div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <form action="#" method="post">
                        <input type="search" name="search" placeholder="Type any keywords...">
                        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">

        <!-- Top Header Area -->
        <div class="top-header-area">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-between">
                    <!-- Breaking News -->
                    <div class="col-12 col-sm-6">
                        <div class="breaking-news">
                            <div id="breakingNewsTicker" class="ticker">
                                <ul>
                                    <li><a href="#">Hello World!</a></li>
                                    <li><a href="#">Welcome to Colorlib Family.</a></li>
                                    <li><a href="#">Hello Delicious!</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Top Social Info -->
                    <div class="col-12 col-sm-6">
                        <div class="top-social-info text-right">
                            <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Navbar Area -->
        <div class="delicious-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="deliciousNav">

                        <!-- Logo -->
                        <a class="nav-brand" href="{% url 'recipe:home' %}"><img src="/static/img/core-img/logo.png" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- close btn -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li class="active"><a href="{% url 'recipe:home' %}">Home</a></li>

                                    </li>
                                    <li><a href="{% url 'recipe:contact' %}">Contact</a></li>
                                    {% if request.user.is_authenticated %}
                                        <li><a href=#>{{request.user.username}}</a></li>
                                    {% else %}
                                        <li><a href="{% url 'users:login' %}">Login</a></li>
                                    {% endif %}
                                </ul>

                                <!-- Newsletter Form -->
                                <div class="search-btn">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </div>

                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->


{% block content %}
{% endblock content %}



    <!-- ##### Follow Us Instagram Area Start ##### -->
    <div class="follow-us-instagram">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h5>Follow Us Instragram</h5>
                </div>
            </div>
        </div>
        <!-- Instagram Feeds -->
        <div class="insta-feeds d-flex flex-wrap">
            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta1.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>

            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta2.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>

            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta3.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>

            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta4.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>

            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta5.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>

            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta6.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>

            <!-- Single Insta Feeds -->
            <div class="single-insta-feeds">
                <img src="/static/img/bg-img/insta7.jpg" alt="">
                <!-- Icon -->
                <div class="insta-icon">
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Follow Us Instagram Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-12 h-100 d-flex flex-wrap align-items-center justify-content-between">
                    <!-- Footer Social Info -->
                    <div class="footer-social-info text-right">
                        <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                    </div>
                    <!-- Footer Logo -->
                    <div class="footer-logo">
                        <a href="index.html"><img src="/static/img/core-img/logo.png" alt=""></a>
                    </div>
                    <!-- Copywrite -->
                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area Start ##### -->

    <!-- ##### All Javascript Files ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static "js/jquery/jquery-2.2.4.min.js" %}"></script>
    <!-- Popper js -->
    <script src="{% static "js/bootstrap/popper.min.js" %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static "js/bootstrap/bootstrap.min.js" %}"></script>
    <!-- All Plugins js -->
    <script src="{% static "js/plugins/plugins.js" %}"></script>
    <!-- Active js -->
    <script src="{% static "js/active.js" %}"></script>
</body>

</html> 